### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by hasobi** [bellshade/Golang#1]
Halo! Saya ingin berkontribusi di repo ini dengan menambahkan beberapa materi dasar, apakah ada guidelines atau materi apa saja yang bisa saya tambahkan?

**Comment by KrisCatDog** [comment]
halo @hasobi , thanks sebelumnya sudah ingin contribute di repo golang ini.
untuk saat ini kami maintainer golang sedang doing research terkait list materi apa saja yang akan di tambahkan kedepannya, setelah fix & so far so good, semua contributor bisa contribute kembali, thanks

**Comment by hasobi** [comment]
Hi @KrisCatDog, terima kasih sudah menjawab, kedepannya saya akan dengan senang hati membantu untuk memberikan PR terkait materi golang.
Issues ini saya tutup ya?! Thanks in advance.
